version: "3"

services:
  dev-db:
    image: postgres:latest
    container_name: eShopDB_dev
    volumes:
      - ${DB_VOLUME_DIR}_dev:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  test_db:
    image: postgres:latest
    container_name: eShopDB_test
    volumes:
      - ${DB_VOLUME_DIR}_test:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - ${DB_PORT_TEST}:5432
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
