version: 2.1

orbs:
  heroku: circleci/heroku@0.0.6

executors:
  rails-executor:
    working_directory: ~/lab-eshop
    docker:
      - image: circleci/ruby:2.5-node
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test

jobs:
  setup:
    executor: rails-executor
    steps:
      # Pull Repository
      - checkout

      # Report environments
      - run: ruby -v
      - run: bundle -v

      # Ruby dependencies
      - restore_cache:
          keys:
            - ruby-dependencies-{{ checksum "Gemfile.lock" }}
            - ruby-dependencies- # fallback to using the latest cache if no exact match is found
      - run:
          name: install Ruby's dependencies
          command: bundle check || bundle install --path vendor/bundle
      - save_cache:
          key: ruby-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # JS dependencies
      - restore_cache:
          keys:
            - yarn-dependencies-{{ checksum "yarn.lock" }}
            - yarn-dependencies-
      - run:
          name: install JavaScript's dependencies
          command: yarn install --cache-folder ~/.cache/yarn
      - save_cache:
          key: yarn-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  test:
    executor: rails-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - ruby-dependencies-{{ checksum "Gemfile.lock" }}
            - ruby-dependencies-
            - yarn-dependencies-{{ checksum "yarn.lock" }}
            - yarn-dependencies-
      - run: bundle check || bundle install --path vendor/bundle
      - run: bin/rails db:create
      - run: bin/rails db:schema:load
      - run: bin/rake test
      - run: bin/rake spec
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
      - run: heroku run rake db:migrate --app $HEROKU_APP_NAME

workflows:
  version: 2
  rails:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - deploy # for CI testing
